name: Build

on:
  push:
    branches:
      - main
      - dev
      - 'release/**'
    tags:
      - '**'
  release:
    types: [published]
  pull_request:
    branches:
      - '**'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/heads/release/')) && github.sha || '' }}
  cancel-in-progress: true

env:
  NPROC: 2

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64]
        include:
        - os: macos-latest
          arch: arm64
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    name: ${{ matrix.os }} - ${{ matrix.arch }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
